language: c
sudo: false

cache:
  directories:
    - $HOME/.stack
    - $HOME/.cabal
    - $HOME/.ghc

before_install:
  - mkdir -p $HOME/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - export STACK_VERSION=1.0.0
  - travis_retry curl -L "https://github.com/commercialhaskell/stack/releases/download/v${STACK_VERSION}/stack-${STACK_VERSION}-linux-x86_64.tar.gz" | gunzip > $HOME/.local/bin/stack
  - chmod a+x $HOME/.local/bin/stack
  - stack setup

install:
  - stack --no-terminal --skip-ghc-check build --only-snapshot

test:
  - stack --no-terminal --skip-ghc-check test --only-snapshot